version: '3'

services:
    nginx:
        restart: always
        image: nginx:1.23-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - media_volume:/app/picasso_test_project/media/
            - static_volume:/app/picasso_test_project/staticfiles/
    server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/server/Dockerfile
        entrypoint: /app/docker/server/django-entrypoint.sh
        volumes:
            - media_volume:/app/picasso_test_project/media/
            - static_volume:/app/picasso_test_project/staticfiles/
        expose:
            - 8000
    worker:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/server/Dockerfile
        entrypoint: /app/docker/server/celery-entrypoint.sh
        volumes:
            - media_volume:/app/picasso_test_project/media/
            - static_volume:/app/picasso_test_project/staticfiles/
        depends_on:
            - server
            - redis
    redis:
        restart: unless-stopped
        image: redis:7.0.5-alpine
        expose:
            - 6379
    db:
        image: postgres:13.0-alpine
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        expose:
            - 5432

volumes:
    media_volume: {}
    static_volume: {}
    postgres_data: {}
